#pip install -r requirement.txt

#flask run -h 127.0.0.1 -p 5000

curl --location --request POST 'http://127.0.0.1:5000/api/submit' \
--header 'Content-Type: application/json' \
--data-raw '{
   "count":3,
   "visits":[
      {
         "store_id":"S01306137",
         "image_url":[
            "https://www.gstatic.com/webp/gallery/2.jpg",
            "https://www.gstatic.com/webp/gallery/3.jpg"
         ],
         "visit_time":"1603879698000"
      },
      {
         "store_id":"S01306141",
         "image_url":[
            "https://www.gstatic.com/webp/gallery/3.jpg"
         ],
         "visit_time":"1603879698000"
      }
   ]

